package com.netflix.contentservice.mapper;

import com.netflix.contentservice.dto.MovieRequest;
import com.netflix.contentservice.dto.MovieResponse;
import com.netflix.contentservice.model.Content;
import org.mapstruct.*;

@Mapper(
        componentModel = "spring",          // makes it a Spring @Component — inject anywhere
        unmappedTargetPolicy = ReportingPolicy.IGNORE  // ignore fields not in source (e.g. id, createdAt)
)
public interface ContentMapper extends BaseMapper<Content, MovieRequest, MovieResponse> {

    @Override
    @Mapping(target = "id",         ignore = true)   // generated by DB
    @Mapping(target = "createdAt",  ignore = true)   // handled by @CreationTimestamp
    @Mapping(target = "updatedAt",  ignore = true)   // handled by @UpdateTimestamp
    @Mapping(target = "videoStatus", constant = "PENDING")  // always DRAFT on creation
    Content toEntity(MovieRequest request);

    @Override
//    @Mapping(target = "videoKey", ignore = true)     // never expose raw S3 key
    MovieResponse toResponse(Content content);

    // ── Partial update (PATCH support) ────────────────────────────────────────
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromRequest(MovieRequest request, @MappingTarget Content content);
}
