spring:
  application:
    name: encodingservice
    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      consumer:
        group-id: encoding-service-group
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.netflix.encodingservice.event"
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: all
        retries: 3

aws:
  region: ap-south-1
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  s3:
    bucket: netflix-encoded-videos  # separate bucket from raw uploads

ffmpeg:
  path: /usr/bin/ffmpeg

kafka:
  topics:
    video-uploaded: video.uploaded.events
    video-encoded: video.encoded.events

server:
  port: 6003

#health check and info endpoint Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized